config/routes.rb
Rails.application.routes.draw do
  resources :pie_graphs
  resources :gauge_graphs
  resources :line_graphs
  resources :bar_graphs
  resources :circle_graphs
  root 'welcome#show'
end

app/models/circle_graph.rb
class CircleGraph < ApplicationRecord
  self.table_name = "circle_graphs"

  validates :score, :total, presence: true
  validates :score, :total, numericality: { only_integer: true }

  validates :score, numericality: { less_than_or_equal_to: :total }, if: :total

end

app/controllers/circle_graphs_controller.rb
class CircleGraphsController < ApplicationController
  before_action :set_circle_graph, only: [:show, :edit, :update, :destroy]

  # GET /circle_graphs
  # GET /circle_graphs.json
  def index
    @circle_graphs = CircleGraph.all
  end

  # GET /circle_graphs/1
  # GET /circle_graphs/1.json
  def show
    redirect_to circle_graphs_url
  end

  # GET /circle_graphs/new
  def new
    @circle_graph = CircleGraph.new
  end

  # GET /circle_graphs/1/edit
  def edit
  end

  # POST /circle_graphs
  # POST /circle_graphs.json
  def create
    @circle_graph = CircleGraph.new(circle_graph_params)

    respond_to do |format|
      if @circle_graph.save
        format.html { redirect_to edit_circle_graph_path(@circle_graph), notice: "Circle graph was successfully created." }
        format.json { render :edit, status: :created, location: @circle_graph }
      else
        format.html { render :new }
        format.json { render json: @circle_graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /circle_graphs/1
  # PATCH/PUT /circle_graphs/1.json
  def update
    respond_to do |format|
      if @circle_graph.update(circle_graph_params)
        format.html { redirect_to edit_circle_graph_path(@circle_graph), notice: "Circle graph was successfully updated." }
        format.json { render :edit, status: :ok, location: @circle_graph }
      else
        format.html { render :edit }
        format.json { render json: @circle_graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /circle_graphs/1
  # DELETE /circle_graphs/1.json
  def destroy
    @circle_graph.destroy
    respond_to do |format|
      format.html { redirect_to circle_graphs_url, notice: "Circle graph was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circle_graph
      @circle_graph = CircleGraph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circle_graph_params
      params.require(:circle_graph).permit(:score, :total)
    end
end

app/views/circle_graphs/_circle_graph_svg.html.erb
<svg style="height:<%= graph.size %>px;width:<%= graph.size %>px;"
     version="1.2" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink" class="graph" aria-labelledby="title" role="img"
     viewBox="0 0 <%= graph.size %> <%= graph.size %>"  preserveAspectRatio="none">
  <title class="title">
    A circle chart showing your Results
  </title>

  <text x="<%= graph.center %>" y="<%= graph.center + 10 %>"
        font-size="30px" text-anchor="middle" fill="#C1C1C1">
    <%= graph.percentage.to_i %>%
  </text>
  <circle cx="<%= graph.center %>" cy="<%= graph.center %>"
          r="<%= graph.radius %>" />
  <path
    class="score_path"
    d="M<%= graph.arc_start %>
      A <%= graph.radius %> <%= graph.radius %> 0 0 1 <%= graph.arc_end_rhs %>
      A <%= graph.radius %> <%= graph.radius %> 0 0 1 <%= graph.arc_end_lhs %>"
    fill="none"
    stroke="#<%= generate_light_color %>"
    stroke-dasharray="<%= graph.percentage_adj %>, <%= graph.circumference %>"
  />
</svg>

app/views/circle_graphs/_form.html.erb
<%= form_with(model: circle_graph, local: true) do |form| %>
  <% if circle_graph.errors.any? %>
    <div id="error_explanation" role="alert">
      <h2><%= pluralize(circle_graph.errors.count, "error") %> prohibited this circle_graph from being saved:</h2>

      <ul>
      <% circle_graph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score,
          placeholder: "Enter a score",
          autofocus: true,
          aria: { "described-by": "score-error" } %>
    <p class="error" id="score-error">
      <%= circle_graph.errors[:score].first %>
    </p>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.number_field :total,
          placeholder: "Enter a total",
          aria: { "described-by": "total-error" } %>
    <p class="error" id="total-error">
      <%= circle_graph.errors[:total].first %>
    </p>
  </div>

  <div class="actions">
    <%= form.submit class: "button purple" %>
  </div>
<% end %>

app/views/circle_graphs/edit.html.erb
<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>Editing Circle Graph</h1>
    </header>

    <div class="page__form">
      <div class="circle_graph">
        <% @circle = SvgDataPlotterGem::Circle.new({score: @circle_graph.score_was, total: @circle_graph.total_was, size: 200}) %>

        <%= render "circle_graphs/circle_graph_svg", graph: @circle %>
      </div>
      <%= render "form", circle_graph: @circle_graph %>
    </div>

    <nav class="page__cta">
      <%= link_to "Back", circle_graphs_path, class: "button pink" %>
      <%= link_to "Delete", @circle_graph, class: "button blue", method: :delete, data: { confirm: "Are you sure?" } %>
    </nav>
  </article>
</section>

app/views/circle_graphs/index.html.erb
<% content_for :title, " - All circle graphs" %>

<% if notice %>
  <p id="notice" role="alert"><%= notice %></p>
<% end %>

<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>Circle Graphs</h1>
      <p><strong>
        Here are some basic SVG circle graphs where it's filling in a percentage

      </strong></p>
    </header>
    <nav class="page__preview">
    <% @circle_graphs.each do |circle_graph| %>
      <%= link_to edit_circle_graph_path(circle_graph), class: "preview_link" do %>
        <div class="circle_graph">
          <% @circle = SvgDataPlotterGem::Circle.new({score: circle_graph.score, total: circle_graph.total, size: 180}) %>

          <%= render "circle_graphs/circle_graph_svg", graph: @circle %>
        </div>
        <span>Update</span>
      <% end %>
    <% end %>
    </nav>
    <div class="page__cta">
      <%= link_to 'New Circle Graph', new_circle_graph_path, class: "button purple" %>
      <%= link_to 'Other Graphs', root_path, class: "button pink" %>
    </div>

    <%= render "shared/code_snippet", graph: "circle" %>
  </article>
</section>

app/views/circle_graphs/new.html.erb
<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>New Circle Graph</h1>
    </header>

    <div class="page__form">
      <%= render 'form', circle_graph: @circle_graph %>
    </div>

    <nav class="page__cta">
      <%= link_to 'Back', circle_graphs_path, class: "button pink" %>
    </nav>
  </article>
</section>