config/routes.rb
Rails.application.routes.draw do
  resources :pie_graphs
  resources :gauge_graphs
  resources :line_graphs
  resources :bar_graphs
  resources :circle_graphs
  root 'welcome#show'
end

app/models/pie_graph.rb
class PieGraph < ApplicationRecord
  self.table_name = "pie_graphs"

  validates :scores, presence: true
  validate :score_values

  # Overrides the default method and turns the string into an array
  def scores=(value)
    if value.is_a? String
      value = value.split(/[, ]+/).reject(&:blank?)
    end
    super
  end

  def score_values
    return unless scores
    scores.each do |score|
      if score < 0
        errors.add(:scores, "Each score must be larger or equal to 0")
      end
    end
  end

end

app/controllers/pie_graphs_controller.rb
class PieGraphsController < ApplicationController
  before_action :set_pie_graph, only: [:show, :edit, :update, :destroy]

  # GET /pie_graphs
  # GET /pie_graphs.json
  def index
    @pie_graphs = PieGraph.all
  end

  # GET /pie_graphs/1
  # GET /pie_graphs/1.json
  def show
    redirect_to pie_graphs_url
  end

  # GET /pie_graphs/new
  def new
    @pie_graph = PieGraph.new
  end

  # GET /pie_graphs/1/edit
  def edit
  end

  # POST /pie_graphs
  # POST /pie_graphs.json
  def create
    @pie_graph = PieGraph.new(pie_graph_params)

    respond_to do |format|
      if @pie_graph.save
        format.html { redirect_to edit_pie_graph_path(@pie_graph), notice: 'Pie graph was successfully created.' }
        format.json { render :edit, status: :created, location: @pie_graph }
      else
        format.html { render :new }
        format.json { render json: @pie_graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pie_graphs/1
  # PATCH/PUT /pie_graphs/1.json
  def update
    respond_to do |format|
      if @pie_graph.update(pie_graph_params)
        format.html { redirect_to edit_pie_graph_path(@pie_graph), notice: 'Pie graph was successfully updated.' }
        format.json { render :edit, status: :ok, location: @pie_graph }
      else
        format.html { render :edit }
        format.json { render json: @pie_graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pie_graphs/1
  # DELETE /pie_graphs/1.json
  def destroy
    @pie_graph.destroy
    respond_to do |format|
      format.html { redirect_to pie_graphs_url, notice: 'Pie graph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pie_graph
      @pie_graph = PieGraph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pie_graph_params
      params.require(:pie_graph).permit(:scores, scores: [])
    end
end

app/views/pie_graphs/_form.html.erb
<%= form_with(model: pie_graph, local: true) do |form| %>
  <% if pie_graph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pie_graph.errors.count, "error") %> prohibited this pie_graph from being saved:</h2>

      <ul>
      <% pie_graph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :scores %>
    <%= form.text_field :scores,
          placeholder: "x, y, z",
          autofocus: true,
          aria: { "described-by": "scores-error" } %>
    <p class="error" id="scores-error">
      <%= pie_graph.errors[:scores].first %>
    </p>
  </div>

  <div class="actions">
    <%= form.submit class: "button purple" %>
  </div>
<% end %>

app/views/pie_graphs/_pie_graph_svg.html.erb
<svg style="height:<%= graph.size %>px;width:<%= graph.size %>px;"
     version="1.2" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink" class="graph" aria-labelledby="title" role="img"
     viewBox="0 0 <%= graph.size %> <%= graph.size %>"  preserveAspectRatio="none">
  <title class="title">
    A pie chart showing your Results
  </title>

  <g class="circles">
    <%= graph.circles %>
  </g>

  <g>
    <%= graph.labels %>
  </g>

</svg>

app/views/pie_graphs/edit.html.erb
<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>Editing Pie Graph</h1>
    </header>

    <div class="page__form">
      <div class="pie_graph">
        <%= PiePresenter.new(self, @pie_graph.scores_was, 180).render %>
      </div>
      <%= render 'form', pie_graph: @pie_graph %>
    </div>

    <nav class="page__cta">
      <%= link_to 'Back', pie_graphs_path, class: "button pink" %>
      <%= link_to 'Destroy', @pie_graph, class: "button blue", method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </article>
</section>

app/views/pie_graphs/index.html.erb
<% content_for :title, " - All pie graphs" %>

<% if notice %>
  <p id="notice" role="alert"><%= notice %></p>
<% end %>
<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>Pie Graphs</h1>
      <p><strong>
        Here are some small SVG pie graphs where it's splitting a circle by percent
      </strong></p>
    </header>
    <nav class="page__preview">
      <% @pie_graphs.each do |pie_graph| %>
        <%= link_to edit_pie_graph_path(pie_graph), class: "preview_link" do %>
        <div class="pie_graph">
          <%= PiePresenter.new(self, pie_graph.scores, 180).render %>
        </div>
        <span>Update</span>
        <% end %>
      <% end %>
    </nav>

    <div class="page__cta">
      <%= link_to 'New Pie Graph', new_pie_graph_path, class: "button purple" %>
      <%= link_to 'Other Graphs', root_path, class: "button pink" %>
    </div>

    <%= render "shared/code_snippet", graph: "pie" %>

  </article>
</section>

app/views/pie_graphs/new.html.erb
<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>New Pie Graph</h1>
    </header>

    <div class="page__form">
      <%= render 'form', pie_graph: @pie_graph %>
    </div>

    <nav class="page__cta">
      <%= link_to 'Back', pie_graphs_path, class: "button pink" %>
    </nav>
  </article>
</section>