config/routes.rb
Rails.application.routes.draw do
  resources :pie_graphs
  resources :gauge_graphs
  resources :line_graphs
  resources :bar_graphs
  resources :circle_graphs
  root 'welcome#show'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    @circle = SvgDataPlotterGem::Circle.new({score: 27, total: 100, size: 200})
    @gauge  = SvgDataPlotterGem::Gauge.new({score: 65, total: 100, size: 180})
  end
end

app/views/welcome/show.html.erb
<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>SVG Graphs on Rails!</h1>
      <p><strong>
        Here are some graphs I made using Ruby to generate SVG's
        Feel free to check out the <%= link_to "code on Github", "https://github.com/Rhiana/presenting_graphs", target: "_blank" %>
      </strong></p>
    </header>
    <nav class="page__preview">
      <%= link_to bar_graphs_path, class: "preview_link" do %>
        <div class="bar_graph">
          <%= BarPresenter.new(self, [21, 8], 30, 200, 180).render %>
        </div>
        <span>Bar Graphs</span>
      <% end %>
      <%= link_to circle_graphs_path, class: "preview_link" do %>
        <div class="circle_graph">
          <%= render "circle_graphs/circle_graph_svg", graph: @circle %>
        </div>
        <span>Circle Graphs</span>
      <% end %>
      <%= link_to gauge_graphs_path, class: "preview_link" do %>
        <div class="gauge_graph">
          <%= render "gauge_graphs/gauge_graph_svg", graph: @gauge %>
        </div>
        <span>Gauge Graphs</span>
      <% end %>
      <%= link_to pie_graphs_path, class: "preview_link" do %>
        <div class="pie_graph">
          <%= PiePresenter.new(self, [25, 66, 11], 180).render %>
        </div>
        <span>Pie Graphs</span>
      <% end %>
      <%= link_to line_graphs_path, class: "preview_link" do %>
        <div class="line_graph">
          <%= LinePresenter.new(self, [23, 7, 36], 40, 180).render %>
        </div>
        <span>Line Graphs</span>
      <% end %>
    </nav>
  </article>
</section>