config/routes.rb
Rails.application.routes.draw do
  resources :pie_graphs
  resources :gauge_graphs
  resources :line_graphs
  resources :bar_graphs
  resources :circle_graphs
  root 'welcome#show'
end

app/models/bar_graph.rb
class BarGraph < ApplicationRecord
  self.table_name = "bar_graphs"

  validates :scores, presence: true
  validates :maximum, presence: true, numericality: { only_integer: true }
  validate :score_value_range

  # Overrides the default method and turns the string into an array
  def scores=(value)
    if value.is_a? String
      value = value.split(/[, ]+/).reject(&:blank?)
    end
    super
  end

  def score_value_range
    return unless scores
    return unless maximum
    scores.each do |score|
      if score > maximum
        errors.add(:scores, "Each score must be smaller or equal to the maximum score")
      elsif score < 0
        errors.add(:scores, "Each score must be larger or equal to 0")
      end
    end
  end
end

app/controllers/bar_graphs_controller.rb
class BarGraphsController < ApplicationController
  before_action :set_bar_graph, only: [:show, :edit, :update, :destroy]

  # GET /bar_graphs
  # GET /bar_graphs.json
  def index
    @bar_graphs = BarGraph.all
  end

  # GET /bar_graphs/1
  # GET /bar_graphs/1.json
  def show
    redirect_to bar_graphs_url
  end

  # GET /bar_graphs/new
  def new
    @bar_graph = BarGraph.new
  end

  # GET /bar_graphs/1/edit
  def edit
  end

  # POST /bar_graphs
  # POST /bar_graphs.json
  def create
    @bar_graph = BarGraph.new(bar_graph_params)

    respond_to do |format|
      if @bar_graph.save
        format.html { redirect_to edit_bar_graph_path(@bar_graph), notice: 'Bar graph was successfully created.' }
        format.json { render :edit, status: :created, location: @bar_graph }
      else
        format.html { render :new }
        format.json { render json: @bar_graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bar_graphs/1
  # PATCH/PUT /bar_graphs/1.json
  def update
    respond_to do |format|
      if @bar_graph.update(bar_graph_params)
        format.html { redirect_to edit_bar_graph_path(@bar_graph), notice: 'Bar graph was successfully updated.' }
        format.json { render :edit, status: :ok, location: @bar_graph }
      else
        format.html { render :edit }
        format.json { render json: @bar_graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bar_graphs/1
  # DELETE /bar_graphs/1.json
  def destroy
    @bar_graph.destroy
    respond_to do |format|
      format.html { redirect_to bar_graphs_url, notice: 'Bar graph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar_graph
      @bar_graph = BarGraph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bar_graph_params
      params.require(:bar_graph).permit(:maximum, :scores, scores: [])
    end
end

app/views/bar_graphs/_bar_graph_svg.html.erb
<svg style="height:<%= graph.height %>px;width:<%= graph.width %>px;"
     version="1.2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="graph" aria-labelledby="title" role="img"
     viewBox="0 0 <%= graph.width %> <%= graph.height %>"  preserveAspectRatio="none">
  <title class="title">
    A bar chart showing your Results
  </title>

  <g class="grid x-grid">
    <%= graph.x_grid_lines %>
  </g>

  <g class="grid y-grid">
    <%= graph.y_grid_lines %>
  </g>

  <g class="labels y-labels">
    <%= graph.scale_labels %>
  </g>

  <g>
    <%= graph.bars %>
    <%= graph.labels %>
  </g>

</svg>

app/views/bar_graphs/_form.html.erb
<%= form_with(model: bar_graph, local: true) do |form| %>
  <% if bar_graph.errors.any? %>
    <div id="error_explanation" role="alert">
      <h2><%= pluralize(bar_graph.errors.count, "error") %> prohibited this bar_graph from being saved:</h2>

      <ul>
      <% bar_graph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :scores %>
    <%= form.text_field :scores,
          placeholder: "x, y",
          autofocus: true,
          aria: { "described-by": "scores-error" } %>
    <p class="error" id="scores-error">
      <%= bar_graph.errors[:scores].first %>
    </p>
  </div>

  <div class="field">
    <%= form.label :maximum %>
    <%= form.number_field :maximum,
          placeholder: "Enter the max score",
          aria: { "described-by": "maximum-error" } %>
    <p class="error" id="maximum-error">
      <%= bar_graph.errors[:maximum].first %>
    </p>
  </div>

  <div class="actions">
    <%= form.submit class: "button purple" %>
  </div>
<% end %>

app/views/bar_graphs/edit.html.erb
<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>Editing Bar Graph</h1>
    </header>

    <div class="page__form">
      <div class="bar_graph">
        <%= BarPresenter.new(self, @bar_graph.scores_was, @bar_graph.maximum_was, 200, 180).render %>
      </div>
      <%= render 'form', bar_graph: @bar_graph %>
    </div>

    <nav class="page__cta">
      <%= link_to 'Back', bar_graphs_path, class: "button pink" %>
      <%= link_to 'Destroy', @bar_graph, class: "button blue", method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </article>
</section>

app/views/bar_graphs/index.html.erb
<% content_for :title, " - All bar graphs" %>

<% if notice %>
  <p id="notice" role="alert"><%= notice %></p>
<% end %>

<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>Bar Graphs</h1>
      <p><strong>
        Here are some basic SVG bar graphs where it's filling in a percentage

      </strong></p>
    </header>
    <nav class="page__preview">

    <% @bar_graphs.each do |bar_graph| %>
      <%= link_to edit_bar_graph_path(bar_graph), class: "preview_link" do %>
        <div class="bar_graph">
          <%= BarPresenter.new(self, bar_graph.scores, bar_graph.maximum, 200, 180).render %>
        </div>
        <span>Update</span>
      <% end %>
    <% end %>
    </nav>
    <div class="page__cta">
      <%= link_to 'New Bar Graph', new_bar_graph_path, class: "button purple" %>
      <%= link_to 'Other Graphs', root_path, class: "button pink" %>
    </div>

    <%= render "shared/code_snippet", graph: "bar" %>
  </article>
</section>

app/views/bar_graphs/new.html.erb
<section class="page">
  <article class="page__content">
    <header class="page__header">
      <h1>New Bar Graph</h1>
    </header>

    <div class="page__form">
      <%= render 'form', bar_graph: @bar_graph %>
    </div>

    <nav class="page__cta">
      <%= link_to 'Back', bar_graphs_path, class: "button pink" %>
    </nav>
  </article>
</section>